### ISSUE TITLE
UEF 1-4 Desync

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-coop-maps#103]
Desync in all coop games i played today (UEF1-4) with 3-4 players. Log of last game (UEF 4) attached:
[game.log.txt](https://github.com/FAForever/faf-coop-maps/files/368175/game.log.txt)

Will try and continue to play to see if reproducable.

**Comment by Katharsas** [comment]
Ok, ill try again after other issue patched.

**Comment by Katharsas** [comment]
Still desync in UEF 1 after first objective.

**Comment by Katharsas** [comment]
Cannot upload logs since Github wont accept my zip files.

**Comment by theeggroll** [comment]
Mission 1: Desync when objective to make mexes is assigned (first 2 minutes)
theeggroll: https://gist.github.com/theeggroll/36dee1792c601553bfa3a39369b01dab
Kalvirox: https://gist.github.com/Kalvirox/64b6a694de5f653bd36becb7bcb64cad
Mission 2: If you give the trucks to ally and then transport them to luthien colony you cant complete the objective (No Desync though)
theeggroll: https://gist.github.com/theeggroll/ce8b014d3cac851f5ee8a60559a254a1
Kalvirox: https://gist.github.com/Kalvirox/e77af8b8322485a8ba847462f6016986
Mission 3: Desyncs when assigned first objective
theeggroll: https://gist.github.com/theeggroll/ae48dc884f443e4abb49583920d15b54
Kalvirox: https://gist.github.com/Kalvirox/50d0ac487be220a7a7cbfc30d8f80b94
Mission 4: JAnus bombers can be constructed. Couldn't capture the Cybran command centers (I tried 5 times)
theeggroll: https://gist.github.com/theeggroll/a0ad0a060b628c8e02bae1f0fed66863
Kalvirox: https://gist.github.com/Kalvirox/d8a0b9bcd0728af12f6f21a68088e1e6

**Comment by Katharsas** [comment]
Tried another game:
Other player was afk, i built mexes, egen and t1 land fac. Then he came back, and the instant he moved, desync. Game log:
[game.log.txt](https://github.com/FAForever/faf-coop-maps/files/607585/game.log.txt)

Vanilla campaign is effectively broken atm : (

**Comment by speed2CZ** [comment]
I've tested it and it doesn't desync for me

**Comment by Katharsas** [comment]
Well it must be coop related since pvp works fine.

Isn't the problem visible in the logs? Or do you rather need replays? Do i need to enable more finegrained logging? I know that non-reproducable bugs are very difficult. If you want me to test something specific, i could do it (since it happens always, i can provide more logs if other people are willing to join my games).

**Comment by TheKeyBlue** [comment]
I actually also had a desync on UEFM1 recently. 
It desynced when it expanded, at first or second map expasion (if i remember correctly)
Don't seem to remember where i put that game.log file, but it didn't seem to have any interesting errors, if i remember correctly.

**Comment by speed2CZ** [comment]
I won the mission with no desync

**Comment by speed2CZ** [comment]
Fixed in fa repo
