### ISSUE TITLE
FA M4 (X1CA_Coop_004) Desync

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#105]
There's a desync just before cinematics for second part of the mission.

@Crotalus can you investigate?

**Comment by Crotalus** [comment]
Took a quick look but replay didn't desync for me. Is it only in multiplayer coop games?

Rushed through mission 1 by killing all the structures and then waited through the cinematics after that. Is it around there the desync is?

**Comment by speed2CZ** [comment]
In-game desync in multiplayer, it showed up a second or two before the cinematics started (after ctrl-ked the first base)
I can try it again tonight with the new patch

**Comment by speed2CZ** [comment]
Either I did something wrong before or it got fixed with the new patch...
