### ISSUE TITLE
Aeon M5 UEF: Attack with transports doesn't seem to work

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#118]
UEF attack with transport is broken. pillar + titan + T3 arty are inside transports, but they stay inside the base. There are also mobile shields that seem to be part of the attack(?) but aren't inside a transport. There is no lack of transports as a dozen are waiting to pick up units.

This creates a silly situation where transports try to defend the base, while carrying landunits.

**Comment by speed2CZ** [comment]
Did you check the log if there was some ereor?
