### ISSUE TITLE
FA 2 doesn't expand

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#12]
WARNING: Error running lua script: ...\gamedata\mohodata.scd\lua\sim\scenarioutilities.lua(64): attempt to concatenate local `chainName' (a table value)
         stack traceback:
         	...\gamedata\mohodata.scd\lua\sim\scenarioutilities.lua(64): in function `ChainToPositions'
         	... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(530): in function <... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua:524>
WARNING: Error running lua script: ...\gamedata\mohodata.scd\lua\sim\scenarioutilities.lua(64): attempt to concatenate local `chainName' (a table value)
         stack traceback:
         	...\gamedata\mohodata.scd\lua\sim\scenarioutilities.lua(64): in function `ChainToPositions'
         	... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(530): in function <... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua:524>
INFO: *DEBUG: Taunt played number 2
INFO: *DEBUG: Taunt played number 1
WARNING: Error running lua script: ...ce\maps\x1ca_coop_002.v0009\x1ca_coop_002_script.lua(740): attempt to call method `SetCustomName' (a nil value)
         stack traceback:
         	...ce\maps\x1ca_coop_002.v0009\x1ca_coop_002_script.lua(740): in function <...ce\maps\x1ca_coop_002.v0009\x1ca_coop_002_script.lua:587>

**Comment by speed2CZ** [comment]
fixed by https://github.com/FAForever/faf-coop-maps/commit/8b30bb1d742c533ad50acfc5c57c9d0570b65dc1 please close
