### ISSUE TITLE
Aeon M2 Cybran Attacks takes too long to spawn

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#120]
First primary objective it to cleanse the city, if you finish it too fast, the other objective to defeat cybran attack is not assigned right away. It has a timer trigger from the beginning of the mission so you might end up without an objective for few minutes.

**Comment by Crotalus** [comment]
Typo, M1P2 -> M1P1

**Comment by speed2CZ** [comment]
#muchBlind
ok, now when I looked at it again, there are actually both M1P1 and M1P2, and there's one more check to end the mission here https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_A02/SCCA_Coop_A02_script.lua#L567
Time to test...

**Comment by speed2CZ** [comment]
everything works "fine"
There's a attack that's launched after several minutes, not depending if you finished objective to kill the city. So there's time where you can end up without any objective, if you're too fast...
