### ISSUE TITLE
Black Day desync

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#121]
Desynced after destroying the order base attacking the civilians

https://gist.github.com/MattDeering/c5a84309229990dcb7a70d93fc9fc23e

**Comment by Bra1nwash3d** [comment]
http://pastebin.com/TUbMzHhV

**Comment by speed2CZ** [comment]
```
warning: Error running lua script: ...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(683): attempt to loop over local `dTable' (a nil value)
         stack traceback:
            ...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(683): in function <...faforever\gamedata\lua.nx2\lua\scenarioframework.lua:678>
```
This is the issue, I assume some wrong dialogue

**Comment by TheKeyBlue** [comment]
Did you not get this WARN message?
`WARN('dTable is nil, ScenarioInfo.DialogueQueue len is ' .. repr(table.getn(ScenarioInfo.DialogueQueue)))`
https://github.com/FAForever/fa/blob/7003fb20f3d1e7f6943ad9a96a1509da9c1ef585/lua/ScenarioFramework.lua#L681

and shouldn't it have crashed here first? 
`not dTable.Flushed`
https://github.com/FAForever/fa/blob/7003fb20f3d1e7f6943ad9a96a1509da9c1ef585/lua/ScenarioFramework.lua#L682

Or am i missing something...

**Comment by speed2CZ** [comment]
This should be fixed now
