### ISSUE TITLE
registration email fail

### ISSUE THREAD

**Issue by pureevilchocobo** [FAForever/faf-coop-maps#128]
i resently tryed to join faf and it sent me an email to verify my account but when i click the link i get this code.

Invalid Key

The authentication key you provided was invalid or expired.

i have tryed 5 times now and still the same result every time.

**Comment by micheljung** [comment]
Hi, while "faf-coop-maps" is not the right repository to report this (it's for Coop-Maps ;-)), I don't want to let you hang. Can you tell me what your username is?

**Comment by pureevilchocobo** [comment]
it wont actualy let me make one. i posted here because the link from the main site sent me here. i was planing on the user name Pureevilchocobo.
