### ISSUE TITLE
FA 3 Infinite Resources

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#13]
keep getting given resources. 1st ras is viable!

**Comment by speed2CZ** [comment]
caused by friendly AI sharing resources, that needs to be changed https://github.com/FAForever/fa-coop/issues/13

**Comment by speed2CZ** [comment]
fixed by https://github.com/FAForever/faf-coop-maps/commit/f6b2d0b5e5aca916162d7f7fb58f121aa8caf37a
