### ISSUE TITLE
FortClarkeAssault - Spawning ACU/Units

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#135]
Today i tried playing FortClarkeAssault with 2 others and in our first try only 1 acu spawned.(no log) We decided to rehost and just spawn acu ourselves. In 2nd try, we did all get ACU, but 1 person didn't get any units.

PS: First lack of ACUs was due to 3rd player being Coop3 instead of Coop2, i think.
PSS: Loss of units from 1 player due to ASF killing a transport.

[forteClarke.zip](https://github.com/FAForever/faf-coop-maps/files/466358/forteClarke.zip)

**Comment by Katharsas** [comment]
Can confirm that there are problems with ACU spawning. When i played with others, we had to cheat to spawn in an ACU for everybody, because only host had one.

**Comment by speed2CZ** [comment]
Yeah you need to take slots in the order in the lobby.
And transports can be killed by ASFs, maybe I should change that.
