### ISSUE TITLE
FortClarkeAssault - No Awhassa Wreck objective

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#136]
The reclaim objective doesn't seem to happen due to GetPosition on nil error.
Maybe the wreck hasn't appeared yet, so the prop search fails?
[fortclarke.zip](https://github.com/FAForever/faf-coop-maps/files/466362/fortclarke.zip)

**Comment by speed2CZ** [comment]
Could not reproduce this, maybe some edge case
