### ISSUE TITLE
FA5 doesn't expand

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#14]
Expanded after killing the first base but did not expand after killing hex 5.

http://pastebin.com/2DfebxWT

Also in Hex 5s base his experimentals did not patrol and fletcher needs more power for his shields.

**Comment by ChrisKitching** [comment]
Looks like the Brackmann crab has an extra bone that's missing from the ordinary Megalith model. GPG fluffed up making this a special unit, so let's just ship the new model with the fa-coop mod.

**Comment by speed2CZ** [comment]
well if you look in the megalith script and blueprint, its still there

OnCreate= function(self)
        CWalkingLandUnit.OnCreate(self)
        self:SetWeaponEnabledByLabel('HackPegLauncher', false)
        if self:IsValidBone('Missile_Turret') then
            self:HideBone('Missile_Turret', true)
        end
    end, 
and it was working until recently, no idea what's going on there

**Comment by speed2CZ** [comment]
I've even tried with original megalith but it still says 'Missile_Turret' is not a valit bone

**Comment by Crotalus** [comment]
Check out model in XRL0404/, seems like XRL0404_lod1.scm have that turret.

**Comment by speed2CZ** [comment]
isn't that what current megalith is using?
https://github.com/FAForever/fa/blob/develop/units/XRL0403/XRL0403_unit.bp#L142

**Comment by Crotalus** [comment]
Ahhhhh!

The XRL0404_LOD0.scm doesn't have the bone, that's the problem. The original XRL_0404_lod0.scm have it though so lost in translation somewhere.

I guess the bone is kinda essential for the mission, otherwise you could just check for valid bone like they do in the Megalith script already (`if self:IsValidBone('Missile_Turret') ...`)

**Comment by speed2CZ** [comment]
So how do we get it back? Should I make a new unit just for coop? Take the original mega, both XRL0403 and XRL0404 and make from it for example XRO0403 and XRO0404 and rename it so it fits?

Or any better idea?

**Comment by Crotalus** [comment]
If the FAF Megalith bone changes isn't important in coop you could grab the original lod0 model from FAs units.scd and use that for coop. i.e. put FA version of `units/XRL0404/XRL0404_LOD0.scm` into coop mod.

**Comment by Crotalus** [comment]
Fixed here
FAForever/fa-coop@56c0d3e7974e05a5236041332ce7ea7df34c27bc
