### ISSUE TITLE
Cybran M2: microwave laser ACU upgrade

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#143]
Your acu can have microwave laser. So you can simply walk into each base (especially since there is barely any t2 pd. Maybe this is a little OP in this setting?
(Again not sure if this is desired behaviour)

**Comment by OCGDFS** [comment]
>> #226. replaced RAS and Laser with T2 and Torpedo. I will pull request for all cybran missions soon. You can close it

**Comment by TheKeyBlue** [comment]
alright, this is part of that global issue, so no need for this mission specific issue.
