### ISSUE TITLE
FA M4 Doesn't Complete

### ISSUE THREAD

**Issue by Cmdrd** [FAForever/faf-coop-maps#148]
Having an issue that has happened 2/2 times for me where FA M4 - Meltdown as UEF doesn't complete after the timer is complete at the end. The "better hold on to your barf bag" plays, and then the screen stays with the cinematic black bars and the mission doesn't properly complete, have to force quit the game to exit. 

I can get logging enabled and play it through again and provide the logs, if that would be useful.

**Comment by speed2CZ** [comment]
It is very useful, without logs I cant fix it

**Comment by Cmdrd** [comment]
Here's the game log file from this: http://pastebin.com/44P5iBYr

**Comment by speed2CZ** [comment]
```
warning: Error running lua script: ...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua(1846): attempt to call method `CreateNuclearExplosion' (a nil value)
         stack traceback:
            ...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua(1846): in function `FakeNuke'
            ...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua(1773): in function <...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua:1694>
```
Code: https://github.com/FAForever/faf-coop-maps/blob/master/X1CA_Coop_004/X1CA_Coop_004_script.lua#L1846
Don't really know too much about projectiles

**Comment by speed2CZ** [comment]
@aeoncleanse can you look at this? I know you were doing something with the nuke explosions so you might now more than me ^^

**Comment by speed2CZ** [comment]
this commit broke it https://github.com/FAForever/fa/commit/4b94f83a3f19ee5d5d5724e4b0f0274bccf9be0e
