### ISSUE TITLE
FA1 Desync

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#15]
Played with Invisible, desynced around when we got T3

http://pastebin.com/Kii4Eacj

**Comment by aeoncleanse** [comment]
It's possible this is not a bug related to coop and you just... desynced. It happens. See if it happens every time, in the same spot.

**Comment by speed2CZ** [comment]
is the desync still hapenning? didnt see any other report on it

**Comment by speed2CZ** [comment]
Didn't get any more report about desyncing, so closing
