### ISSUE TITLE
Count units of all human players

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#159]
There are two new function https://github.com/FAForever/fa-coop/pull/45
`ScenarioFramework.GetNumOfHumanUnits(cat, area)`
`ScenarioFramework.GetListOfHumanUnits(cat, area)`
for easy counting human player units or getting a list of them.

This will be mostly used in adaptive counter attacks. Currently the mission check only for units of `Player` army

For an example replacing

``` LUA
if(table.getn(ArmyBrains[Player]:GetListOfUnits(categories.ALLUNITS - categories.WALL, false)) < 400) then
```

with

``` LUA
if ScenarioFramework.GetNumOfHumanUnits(categories.ALLUNITS - categories.WALL) < 400 then
```

or another one (this one actually checks for all human players)

``` LUA
local num = 0
for _, player in ScenarioInfo.HumanPlayers do
    num = num + table.getn(ArmyBrains[player]:GetListOfUnits((categories.MOBILE * categories.AIR) - categories.TECH1, false))
end
```

with:

``` LUA
local num = ScenarioFramework.GetNumOfHumanUnits((categories.MOBILE * categories.AIR) - categories.TECH1)
```

**Comment by TheKeyBlue** [comment]
i'll start with Aeon missions
