### ISSUE TITLE
FA 3 killed engies before ahwassa was started.

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#16]
Teleported over with coms and killed everything, did not register the objective.

**Comment by speed2CZ** [comment]
just checked, its not possible to teleport there before objective is assigned, since map expands during cinematics and objective is aassigned right after that.
lets close this

**Comment by MattDeering** [comment]
Then it was the next objective didn't spawn. Will try again and see if it happens.
