### ISSUE TITLE
_save files stil contain old BuildCondition functions

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#160]
I noticed some _save files still have pointers to the original Buildconditions.
example:
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E01/SCCA_Coop_E01_save.lua#L10207

**Comment by speed2CZ** [comment]
Yeah, I checked like 4 random vanilla missions and didnt find it there. I will check them all then

**Comment by TheKeyBlue** [comment]
I did already and only found it in 2 missions. See my pull request.
