### ISSUE TITLE
FA M5: bad unit blueprint name (url0307)

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#169]
After a minute or so in the mission, the following error message pops up repeatedly in the log (no stacktrace)

Passed in a bad unit blueprint name (url0307) to FindAvailableFactory!

**Comment by speed2CZ** [comment]
This is bug from original mission.  Wrong template somewhere in this file https://github.com/FAForever/fa/blob/develop/lua/AI/OpAI/BasicLandAttack_save.lua
unit 0307 is T2 shield for aeon/uef, so I assume it tried to convert the template to cybran for mobile stealth, but that has 0306 ID
