### ISSUE TITLE
Prothyon

### ISSUE THREAD

**Issue by quark036** [FAForever/faf-coop-maps#17]
Create an option to launch Speed2's Prothyon mission, rather than hosting one of the old missions and changing maps.

**Comment by Sheeo** [comment]
This should be a simple matter of adding the map to the database. Is the map ready for the general public?

**Comment by quark036** [comment]
You'd have to ask speed2 to make sure, he put up a completed version on the forums, I don't know if he wants to make more changes or if he's ok with adding it.

**Comment by quark036** [comment]
I asked him and he said he wants us to wait until later when he releases a final version.

**Comment by Sheeo** [comment]
In this case I'm closing this issue, thanks for the report though :)
