### ISSUE TITLE
UEF M5: Lazy variable issue

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#172]
At the start of the mission you get error messages like this:

WARNING: Error running OnFrame script in CScriptObject at 125d5d80: ...liance\gamedata\lua.scd\lua\ui\game\announcement.lua(93): error evaluating lazy variable: ... alliance\gamedata\mohodata.scd\lua\maui\control.lua(35): error evaluating lazy variable: ... alliance\gamedata\mohodata.scd\lua\maui\control.lua(37): circular dependency in lazy evaluation for variable [Set lazyvar.ExtendedErrorMessages for extra trace info]

**Comment by speed2CZ** [comment]
I think it tries to play this dialogue and somehow it fails https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E05/SCCA_Coop_E05_script.lua#L416
Since almost at the same time it quits NIS mode. That's my guess
