### ISSUE TITLE
allow com t2/t3 upgrade as soon as you have access to t2/t3 tech

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/faf-coop-maps#198]

**Comment by speed2CZ** [comment]
Are there missions where this happens? I know there are some where you have only like T2 mex and Pgen allowed and you get the upgrade.
From balance point of view it's not a big problem since T2 isnt exactly a combat upgrade in current patch.

**Comment by OCGDFS** [comment]
i think it was the case in E02

**Comment by OCGDFS** [comment]
i will fix this in #226
