### ISSUE TITLE
FA 4 doesn't expand after first objective

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#2]
warning: Error running lua script: ...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua(445): attempt to call method `GetListOfUnits' (a nil value)
         stack traceback:
         	...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua(445): in function <...ce\maps\x1ca_coop_004.v0010\x1ca_coop_004_script.lua:410>
debug: Loading module '\000/units/ura0302/ura0302_script.lua\000'
debug: Loading module '\000/units/uea0304/uea0304_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff005a9) supplied in a pose update.
debug: Loading module '\000/lua/ui/dialogs/keybindings.lua\000'
debug: Loading module '\000/lua/keymap/keydescriptions.lua\000'
debug: Loading module '\000/lua/keymap/properkeynames.lua\000'
debug: Loading module '\000/lua/keymap/keycategories.lua\000'
debug: Loading module '\000/units/xra0305/xra0305_script.lua\000'
info: CWldSession::DoBeat() unknown entity id (0x2ff0028d) supplied in a pose update.
warning: Error running lua script: ... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(530): ERROR: Invalid Chain Named- M2_Seraph_LandDef_3_Chain
         stack traceback:
         	[C]: in function `error'
         	...\gamedata\mohodata.scd\lua\sim\scenarioutilities.lua(64): in function `ChainToPositions'
         	... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua(530): in function <... alliance\gamedata\lua.scd\lua\scenarioplatoonai.lua:524>
info: syncing max ping markers: \00015
info: GPGNET: setting nat handler to 0x00000000
info: CNetTCPBuf::Read(): recv() failed: WSAEINTR

**Comment by aeoncleanse** [comment]
Solved
