### ISSUE TITLE
Co-op Maps wont expand

### ISSUE THREAD

**Issue by Aerospacespark** [FAForever/faf-coop-maps#204]
The Coop maps, a lot of the times wont expand, after the first part is done. the enemy's come like it did expanded but it didn't so you just sit there and the map takes a big shit and all the fun and hard work is killed. plz look into this dankz.

**Comment by speed2CZ** [comment]
You will have to tell us which ones don't expand, in what part and include game.log

**Comment by Aerospacespark** [comment]
it seems to happen on any map coop map really, I'll try to get a recording of it or something but for exp in the first mission after you kill the aeon commander  a lot of the time the map doesn't expand same with other maps after you did a objective the map takes a big shit and doesn't expand. idk how to find the game log or whatever it is, doesn't even give me a error it just sits there and doesn't do anything

**Comment by TheKeyBlue** [comment]
Yes please post a replay in which it happens.
You can get logs by doing what is explained in [Reporting_Technical_Issues](http://wiki.faforever.com/index.php?title=Reporting_Technical_Issues)

**Comment by Aerospacespark** [comment]
https://www.mediafire.com/?400z6c9wof56n8m

don't mind my noob skillz

**Comment by Aerospacespark** [comment]
Do you need anything else other then the log or are we good here for now?

**Comment by TheKeyBlue** [comment]
Ok i found the issue. Thanks for reporting.

Could you also provide us with replays of the other maps that don't expand? (or atleast their names)

**Comment by Aerospacespark** [comment]
The base supcom camp coop maps wont expand, 
  Another one would I say is the station assault in custom missions after the acu drops the map doesn't expand.

**Comment by speed2CZ** [comment]
That should be all mission
