### ISSUE TITLE
Cybran Mission 4 Mainframe Tango - Aeon commander death cut scene plays twice

### ISSUE THREAD

**Issue by Chafe10** [FAForever/faf-coop-maps#213]
When you kill the Aeon commander after the Mainframe EMPs the base, The death cut scene plays twice.

I have attached the replay and game.log just in case.

[Cybran4MainframeTango.zip](https://github.com/FAForever/faf-coop-maps/files/584705/Cybran4MainframeTango.zip)

**Comment by speed2CZ** [comment]
Currently there's a trigger to call the function with the cutscene https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_R04/SCCA_Coop_R04_script.lua#L1151

I think I fixed similar issue by removing the trigger and instead setting callback function to the objective where you are suppote to kill the ACU, which is this one https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_R04/SCCA_Coop_R04_script.lua#L1511

Try that.
