### ISSUE TITLE
FA M5: Can't repair megalith

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#220]
Mission tells you to repair the megalith when it is low hp, but due to build restrictions you can't do it.

**Comment by OCGDFS** [comment]
is there a way to separate the repair function from the restrictions? would be the easiest way.

**Comment by speed2CZ** [comment]
Will get solved in fa repo https://github.com/FAForever/fa/issues/1753

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/fa/commit/309f0fd376d8068bbb9691bd5d439022ed107537
