### ISSUE TITLE
FA M6 Desync warning

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-coop-maps#232]
Desync warning about when fletcher is revealed (i think it happened in all 3 games today). It seems like its not a real desync, players still seem to be in sync mostly.

[game.log.txt](https://github.com/FAForever/faf-coop-maps/files/650347/game.log.txt)
[5530777-Katharsas.fafreplay.txt](https://github.com/FAForever/faf-coop-maps/files/650366/5530777-Katharsas.fafreplay.txt)

**Comment by speed2CZ** [comment]
Fixed in fa repo
