### ISSUE TITLE
FortClarke - Percies don't get triggered

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#242]
https://github.com/FAForever/faf-coop-maps/blob/master/FortClarkeAssault/FortClarkeAssault_script.lua#L537

Player's ACUs are not in `ScenarioInfo.CoopCDR` table anymore.

**Comment by TheKeyBlue** [comment]
probably cause they don't get put in the table here: 
https://github.com/FAForever/faf-coop-maps/blob/master/FortClarkeAssault/FortClarkeAssault_script.lua#L229
