### ISSUE TITLE
Fort Clarke Assault V10

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-coop-maps#243]
I've played the Fort Clarke Assault mission with 2 friends of mine today and encountered some bugs.
After the 2nd expension (the one when you get attacked by t4 units) the Chicken you get as reinforcement were quite damaged (somewhere in the yellow) and damaged the base of the 2nd player.
The t3 Subs you get there disappeared when the owner tried to gift them.
The cybran ACU was not there at all (i think it should be Tokyto).
After killing the UEF ACU (Gorton) we got lots of desync messages.
When the AEON ACU got destroyed there was a voiceline that just had "Seraphim message" or something in the text and no actual sound.
Crash upon finishing the mission.
replay id: 5671922

**Comment by PhilipJFryFAF** [comment]
Took a look at the replay and the 2 chicken that came in as support also spawned 2 ion storms :>

**Comment by speed2CZ** [comment]
Damaged chicked is fixed in game repo. The ion storm is no longer triggered by giving the unit.
T3 subs can be given now as desapreading restricted units is fixed there as well.
Cybran ACU has a clock.
And the objective to kill the 3 ACU should be fixed here #262
