### ISSUE TITLE
FA M6 Friendly nukes

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#281]
If some other player than the first one captures the control center, it will shoot own nukes on the player and the objective isnt marked as finished.

**Comment by TheKeyBlue** [comment]
The scripting can control a captured unit?
Interesting

**Comment by speed2CZ** [comment]
This is the problem, it handles only Player1
https://github.com/FAForever/faf-coop-maps/blob/master/X1CA_Coop_006/X1CA_Coop_006_script.lua#L1482

**Comment by TheKeyBlue** [comment]
ah its not actually a nuke that gets captured. Just a civ building.
