### ISSUE TITLE
Cybran M4 Mainframe Tango - Node 2 no mission Progression

### ISSUE THREAD

**Issue by ShadowT3mplar** [FAForever/faf-coop-maps#282]
After defending the second node from the bugged amount of enemy units, the game will have Rhiza speak twice and then it will not progress anymore.

However, each time I have played, after capturing the first node the game will desync.

Only waves of enemy fighters and bombers will harass your starting location but the enemy units that are meant to be transported to the second node don't move.

Have only tested this with 2 players but it was consistent across the 4 times that we tried.

[game.zip](https://github.com/FAForever/faf-coop-maps/files/1082132/game.zip)

[6369721-Shadowtemplar.zip](https://github.com/FAForever/faf-coop-maps/files/1082134/6369721-Shadowtemplar.zip)

**Comment by speed2CZ** [comment]
This log isnt usable for me, its 28m lines of warning about the sound issue (you should switch to stereo)
so I cant find anything usefull in there.
