### ISSUE TITLE
UEF M6 - Black Sun Fire Button

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-coop-maps#288]
We were two players. At the end you are supposed to select the Black Sun Building and click the button, and this should cause the outro video to be played, but clicking the button does nothing (also tried gifting Black Sun to other player).
[game.log.txt](https://github.com/FAForever/faf-coop-maps/files/1270739/game.log.txt)

**Comment by speed2CZ** [comment]
replay please

**Comment by Katharsas** [comment]
[6719166-Katharsas.zip](https://github.com/FAForever/faf-coop-maps/files/1272232/6719166-Katharsas.zip)

**Comment by speed2CZ** [comment]
Just tested it and it works correctly
