### ISSUE TITLE
Tha Atha Aez - Broke when commanders have to teleport out near end

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/faf-coop-maps#317]
When playing the Coop map Tha Atha Aez, the commanders get stuck or have an issue teleporting out near the end of the campaign. I uploaded the replay to show what I am talking about. It is at the very end. We can't progress, because I think path finding or something interferes with the map. I am running the latest version as of 11/19/17.

Thanks,
Aaron

[7076136-Revekius.zip](https://github.com/FAForever/faf-coop-maps/files/1485754/7076136-Revekius.zip)

**Comment by speed2CZ** [comment]
Watching the replay now, it's desynced right away >.<

Do you mean the retreating commanders, that gate in, walk to your base and gate out?

**Comment by Naluvajko** [comment]
Looks like mission gets stuck if ACU of host dies.
