### ISSUE TITLE
Cybran Mission 1: Liberation radar bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-coop-maps#320]
capturing the radar doesn't trigger the objective and thus the player is stuck
forum [post](http://forums.faforever.com/viewtopic.php?f=78&t=13904&p=158363#p158363)
[Uploading Mission1Cybran.zip…](log+replay)

**Comment by speed2CZ** [comment]
No error in the log >.<

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/fa-coop/commit/0a376569201856103aaf4fd1f2d51755920ce9fa
