### ISSUE TITLE
Aeon M5 - Mission gets stuck

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-coop-maps#333]
Mission got stuck after second expansion: We killed UEF commander in his base, but nothing happened after that.
[logs.zip](https://github.com/FAForever/faf-coop-maps/files/2108632/logs.zip)
Replay:
[8104466-Katharsas.zip](https://github.com/FAForever/faf-coop-maps/files/2108633/8104466-Katharsas.zip)

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/faf-coop-maps/commit/13163252d04287ff6b6f409d06670d6992e45291
