### ISSUE TITLE
Cybran 4. Objective 1 Commander does not die/teleport/whatever

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#34]
Cutscene for commander triggers, objective completes, commander stays where it is and will not go lower than 2800 health.

Replay: 3700892

https://gist.github.com/MattDeering/eef95a4992f21891d0c2
https://gist.github.com/MattDeering/440cb0efdef662afdb16

Also there is some kind of audio error. not sure if map or coop related.

**Comment by theeggroll** [comment]
My logs from same game (I was host)
https://gist.github.com/theeggroll/7bc0536217dacc3d1d84
https://gist.github.com/theeggroll/928d839a08b4b0b04493

**Comment by speed2CZ** [comment]
fixed https://github.com/FAForever/fa/commit/5640ee708599cf10e6ca8531cc31a2c003103f28
close please
