### ISSUE TITLE
Cybran M6: Mission does not start

### ISSUE THREAD

**Issue by expipiplus1** [FAForever/faf-coop-maps#343]
The map starts expanded and the player's ACU never spawns.

I'm not sure of the correct fix, but removing this line and promising to oneself not to create the Absolver works for me.

This line specifically prevents the scenario from loading correctly: https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_R06/SCCA_Coop_R06_script.lua#L302

The error in the Moho log is:

```
WARNING: BeginSession() failed: attempt to get as UserData a nil value
         stack traceback:
         	[C]: ?
         	...ce\maps\scca_coop_r06.v0016\scca_coop_r06_script.lua(302): in function `OnStart'
         	...:\home\j\.faforever\gamedata\lua.nx2\lua\siminit.lua(235): in function <...:\home\j\.faforever\gamedata\lua.nx2\lua\siminit.lua:224>
         	...:\home\j\.faforever\gamedata\lua.nx2\lua\siminit.lua(375): in function <...:\home\j\.faforever\gamedata\lua.nx2\lua\siminit.lua:371>
         	...:\home\j\.faforever\gamedata\lua.nx2\lua\siminit.lua(454): in function `BeginSession'
```

**Comment by expipiplus1** [comment]
Thanks!

**Comment by speed2CZ** [comment]
It will take one of the server admins to release it, so soon™
