### ISSUE TITLE
Cybran 5 buglist

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#35]
T3 AA should be removed
Map did not expand past objective 1
theeeggroll was able to self destruct and the mission did not end.
I could not ctrl k (pop up options against easy way out)
sound bug present. will put it in coop bugs if it happens on more maps
Walls

logs:
https://gist.github.com/MattDeering/f15b4c994740f63a9569
https://gist.github.com/MattDeering/3fbaa736194affcce81c

theeggrolls logs:
https://gist.github.com/theeggroll/0f4c1f7d7d575aee2a83
https://gist.github.com/theeggroll/4de5c3300ba0d719d4cd

**Comment by speed2CZ** [comment]
T3 AA should be removed: fixed by #38
Map did not expand past objective 1: fixed by #27

**Comment by speed2CZ** [comment]
most of these should be fixed, close and if something create a new issue
