### ISSUE TITLE
Cybran M2 script error

### ISSUE THREAD

**Issue by BrickBee** [FAForever/faf-coop-maps#365]
I got this script error playing coop on medium difficulty that prevented further progression:

> WARNING: Error running lua script: attempt to use as string a nil value
>          stack traceback:
>          	[C]: in function \`CreateEmitterOnEntity'
>          	...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(73): in function <...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua:69>
>          	...faforever\gamedata\lua.nx2\lua\defaultexplosions.lua(275): in function \`CreateWreckageEffects'
>          	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(1680): in function \`CreateWreckageProp'
>          	...rever\gamedata\lua.nx2\lua\sim\scenarioutilities.lua(1832): in function \`CreateArmyGroup'
>          	...ce\maps\scca_coop_r01.v0017\scca_coop_r01_script.lua(974): in function \`Part3SpawnEasternUnits'
>          	...ce\maps\scca_coop_r01.v0017\scca_coop_r01_script.lua(853): in function \`callbackFunction'
>          	...\faforever\gamedata\lua.nx2\lua\scenariotriggers.lua(173): in function <...\faforever\gamedata\lua.nx2\lua\scenariotriggers.lua:152>

I have extracted scenarioutilities.lua from lua.nx2 (and nx5) to check for the error, but both end after line ~1600 with CreateArmyGroup being around line 800. Thus I assume there is a different file version somewhere. Only UI mods were used.

**Comment by Uveso** [comment]
The error was in `lua\effectutilities.lua(73)` (line 73),
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/EffectUtilities.lua#L73
The command CreateEmitterOnEntity() failed because it expected an sting as argument but got nil.
(it needs 3 arguments, object, army and Effect)

The CreateEmitterOnEntity() is part of the function CreateRandomEffects()

CreateRandomEffects was called from `defaultexplosions.lua` line 275, function CreateWreckageEffects:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/defaultexplosions.lua#L275

CreateWreckageEffects was called from `unit.lua` line 1680, function CreateWreckageProp:
https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L1680

This way you can trace back the function calls.

**Comment by Uveso** [comment]
Hooking is logged inside the game.log
Just search the log for ScenarioUtilities.lua and you will find it.

An example with simInit.lua:
`info: Hooked /lua/simInit.lua with /mods/ai-uveso/hook/lua/simInit.lua`

When we look at the 3 arguments: object, army and Effect.
Object is a c-object. (the unit)
army is the indexnumber for the army. So its a integer.
Effect is the name of the effect. Should be the string we are missing.

You can also test a value and dump the type of it:
LOG( type( army ) )
will print 'number'

**Comment by BrickBee** [comment]
I found the cause of the error that I have reported initially, and with it the reason why people get occasional _random_ errors (pun intended): The random function is broken.
Yes, that's a bold statement to make, but I have proof, the root-causes (yes, two distinct ones) and a solution for them.

### The actual error
Let's get back to the callstack that I posted for this.
In defaultexplosions.lua there's this call for a small wreckage:
`emitters = CreateRandomEffects(prop, obj.Army, EffectTemplate.DefaultWreckageEffectsSml01, 1)`
This then goes to effectutilities.lua which randomly chooses an entry from the passed effect template table above.
`CreateEmitterOnEntity(obj, army, EffectTable[util.GetRandomInt(1, NumTableEntries)])`

The table that was passed has 4 static entries that are set up on startup and it is not modified afterwards.
Thus this calls util.GetRandomInt(1, 4) which returns an integer in the range [1,4] to select a valid table entry.
In the case of my error the function returned 5, selecting an non-existent entry, and thus nil, causing the error.
How could this happen?

### The first root-cause
Here is the function defined in utilities.lua
```
function GetRandomInt(nmin, nmax)
    return math.floor(Random() * (nmax - nmin + 1) + nmin)
end
```
When looking at this from a purely mathematical standpoint, the function is _guaranteed_ to return a number in the interval [1,4] when 1,4 are passed as parameters and the built-in Random() returns [0,1), however it does not do so. Instead it returns [0,1]. So when it returns 1 we get 1 * (4-1+1)+1 = 5. That then leads to the out-of-bounds table access and the nil.
Proof:
`simlua while true do local rnd = Random() if(rnd) >= 1 then LOG("Too big!") LOG(rnd) break end end LOG("done")`
Running this in the in-game console freezes the game for a second and then exits, as it got a 1 from the RNG.
Thus, the functions that use Random() for generating a number within a specific interval need to be fixed.
This is the first root-cause for the out-of-bounds table access. Now let's move on to the second one.

### The second root-cause
Even if Random() would return [0,1) the GetRandomInt() would still return 5 occasionally in the case mentioned above. However I just wrote that it is _guaranteed_ to return [1,4], and thus it is impossible to get a 5, right? That's still true, from a purely mathematical point of view. The second issue is now caused by code.
If Random() returns 0.99999994039536, then the formula mentioned above will give us 4.99999976158144, which math.floor() then floors down to a 4. That would be true in theory, but is unfortunately wrong in practice, at least when it comes to Supreme Commander.
Proof:
`simlua LOG(0.99999994039536 * 4 + 1)`
This will print "5". You can of course check `if >= 5` to make sure it's not an output formatting issue, but it will confirm what I wrote above. If you run that calculation in stand-alone Lua console you'll get the correct 4.999...  so what's wrong here?

The 0.999 number is the largest possible 32 bit floating point value that's < 1, so all mantissa bits are set.
[Supreme Commander sets](https://gafferongames.com/post/floating_point_determinism/) the CPUs floating point precision to "fast", 24 bits, instead of the more precise 53 or 64 bit setting:
```
_controlfp(_PC_24, _MCW_PC)
_controlfp(_RC_NEAR, _MCW_RC)
```
Due to this setting and the "near" rounding, the above calculation gives us an incorrect result, a 5.
This is a big issue, meaning that _all_ calculations with numbers that are very close to the next-bigger integer could flip over to that, anywhere in the script. Lua uses double precision internally, but only gets single-precision results due to this setting.

### Improvement?
Increasing the precision via the setting would result in the intended number behavior within the embedded Lua. Yet it should only be set for the simulation, not for the GFX code, as that would slow things down there. That'd be a bit of effort to do.
An easier but hacky fix is to simply set `_controlfp(_RC_DOWN, _MCW_RC)`.
Rounding down by default will give a correct result for the calculation above, but may have unknown side-effects as there might be code that relies on the previous behavior.
You can test it by patching your FA ForgedAlliance.exe at offset 0x33D448.
O: 80 F5 C0 00 68 00 00 **03 00** 68 00 **00 02** 00 E8 9A
P: 80 F5 C0 00 68 00 **03 00** 00 68 00 **01 00** 00 E8 9A
Everything still seems to work normally, but I did not test this extensively. **Do not** run MP games together with _unpatched_ clients with this change. They will desync.

### Paths to a solution
Changing the precision setting would give us the desired correct behavior _everywhere_ in the Lua script, yet that could trigger unforeseen issues _everywhere_ else.
If we can be reasonably sure that all code (of all mods) uses the utilities.lua functions for random intervals, then changing those would be a more surgical solution without unintended side-effects. DefaultExplosions, BlackOps and RKS Explosions mod use that at least. Any other code that uses non-integers for table indexing or bounded calculations could still break due to the precision/rounding issue, but maybe there is no script that does so. There is some Random() usage in the other scripts, but apparently not for table indexing.

### The solution
Change GetRandomInt to this function (hah, Random() already supports what was coded there):
```
function GetRandomInt(nmin, nmax)
    return Random(nmin, nmax)
end
```
The GetRandomFloat function is not affected and thus does not need to be changed.

### Bonus
GetRandomOffset2 is broken, because Random returns integers when called with parameters, thus -1, 0, or 1, and not floats in that interval as the author of that function assumed. Fixing it would make our explosions/debris look nicer.
So replace `Random(-1.0, 1.0)` with `Random() * 2 - 1`

By the way, I still find debugging in this environment rather inefficient. Having proper callstacks for hooked functions, detailed API error messages and an on-screen log would help. Having a built-in Lua debugger would certainly also be nice.

**Comment by Uveso** [comment]
Wow BrickBee, nice comment!

As i can see KionX has already a fix for it. Great! :D

**Comment by speed2CZ** [comment]
Fixed in the game repo
