### ISSUE TITLE
UEF 2

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#37]
Aeon counterattack didn't come.
No support factories. 
Could build walls

https://gist.github.com/MattDeering/83c6dde47d09b3fc7c53
https://gist.github.com/MattDeering/b18036aa0d48ad50d111

theeggrolls logs:
https://gist.github.com/theeggroll/df430ba9bdc9ceefb6ac
https://gist.github.com/theeggroll/4889fef2a445b6a29f97

**Comment by speed2CZ** [comment]
attack comes after 5-7 minutes, tested
support factories fixed by https://github.com/FAForever/faf-coop-maps/commit/35bd54efd1d25ed2319b5ebf82af6afcbf70245c
we discussed walls, keeping them allowed for now
