### ISSUE TITLE
Cybran M4 - Not progressing to stage 3

### ISSUE THREAD

**Issue by KyleLomen** [FAForever/faf-coop-maps#401]
# Brief: 
Upon capturing and defending the second node, the mission breaks and does not reveal the next nodes or give an objective.

# Suspected Cause:
On line 1386 of the log file there is this error:
```
warning: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(5377): Attempt to set attribute 'CanTakeDamage' on boolean
         stack traceback:
         	[C]: in function `error'
         	...ata\faforever\gamedata\lua.nx2\lua\system\config.lua(14): in function <...ata\faforever\gamedata\lua.nx2\lua\system\config.lua:13>
         	...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(5377): in function `SetCanTakeDamage'
         	...ce\maps\scca_coop_r04.v0019\scca_coop_r04_script.lua(905): in function <...ce\maps\scca_coop_r04.v0019\scca_coop_r04_script.lua:802>
```
Checking out the scca_coop_r04_script.lua file on lines 901-905:
```
    -- Mainframe
    -- Needs to be invincible
    ScenarioInfo.Mainframe = ScenarioUtils.CreateArmyUnit('Neutral', 'Mainframe')
    ScenarioInfo.Mainframe:SetCustomName(LOC '{i R04_MainframeName}')
    ScenarioInfo.Mainframe.SetCanTakeDamage(false)
```
It has been several years since I last worked with lua, but shouldn't `ScenarioInfo.Mainframe.SetCanTakeDamage(false)` instead be `ScenarioInfo.Mainframe:SetCanTakeDamage(false)` with a colon instead of a dot? Assuming that I remember correctly, what is written here is trying to set `false.CanTakeDamage = nil` which makes no sense. In the game, the mainframe was created although it could be damaged however we did not receive vision of the nodes or the mainframe like the next part of the script says we should have.

I do apologize if this comes across as a bit pretentious, I am not confident that I remember this correctly otherwise I would have made a pull request directly. Also, it does seem like this mission works for other people, so maybe this is not the main problem at all. Although it could be related to the addition of boolean to `lua/system/config.lua` in https://github.com/FAForever/fa/commit/51e21478bd1e0300f2edd5feaa710a9b8cb52033. 

# Files:
Replay: https://replay.faforever.com/19029580
Log: [game_19029580.log](https://github.com/FAForever/faf-coop-maps/files/10442649/game_19029580.log)

**Comment by Garanas** [comment]
You're correct 😄 ! There should be a colon `:` instead of a `.` there. I'll pick it up and make sure it is part of the next release. For now you can fix this manually by applying your suggestion manually - all players in the lobby would need to do this in order for the game to not desync.

**Comment by speed2CZ** [comment]
Im kinda surprised that this is the first report about this issue, considering it's been broken for 5 years
