### ISSUE TITLE
UEF Coop Map won't launch and does not appear in lobby despite being in maps folder

### ISSUE THREAD

**Issue by alexpikx** [FAForever/faf-coop-maps#403]
Hi, 

I have trouble launching UEF vanilla missions 1,3 and 6. 

When I select one of them in the launcher, create a lobby and launch the game, the game will stay in loading forever. 

When I try to change the map in the lobby, I can see the map if I choosed it in FAF client but if I create a lobby with another map, I cannot see the map in the map selection of the lobby. 

In this case I created the lobby with mission 3. Map of mission 3 appears correctly but maps for missions 1 and 6 does not appear.
![Lobby_map_not_apearing](https://user-images.githubusercontent.com/28343470/216790626-66576094-e36e-4637-a960-cc80715debcc.PNG)

Even if they have have been already downloaded in the map folder :
![FA_map_folder](https://user-images.githubusercontent.com/28343470/216790625-961e0109-14ab-400e-b6be-c6d20e27fecd.PNG)

When I select the map of mission 3 (without any mod)
![Error_message_lobby_when_selecting_map](https://user-images.githubusercontent.com/28343470/216790667-e2189b3a-cba5-4054-84de-6ac1c4ffe730.PNG)

I cannot understand why those 3 maps are troublesome, for instance I do not have any problem with mission 5. 

Do you think this is a problem with my setup ? Or with the maps ? 
Do those kinds of problem belong here ? If not, where can I ask for help for this ?

Thanks for your support
Greetings

**Comment by speed2CZ** [comment]
Try to delete them and download again

**Comment by alexpikx** [comment]
okay I deleted all the older versions af the maps as well and it worked ! 
Thanks for the support
