### ISSUE TITLE
Player ACU death triggers not working

### ISSUE THREAD

**Issue by Dhomie** [FAForever/faf-coop-maps#409]
Player ACU death triggers (operation failure by ACU death) seem to only work if only 1 player is present in a match.
If more than 1 players are present, player ACU deaths don't trigger any mission failure whatsoever, even if all ACUs die.

Tested it with stock AIs for player slots, here's a replay ID: #20324344
Replay URL: https://replay.faforever.com/20324344

**Comment by speed2CZ** [comment]
Is this still a thing? In my current local testing, the game ends as expected when any of the commanders die

**Comment by speed2CZ** [comment]
Nvm, looks like the coop update hasnt been released, it will be fixed with the next patch https://github.com/FAForever/fa-coop/commit/3d219cfa34f91cc1c4860c8b57bfa26bb393a551
