### ISSUE TITLE
Custom unit names give error

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#44]
Example:
WARNING: unknown localization directive: unknown: key: BlackSunCannon
This warning gets spammed if you hover over unit with custom name or select it. Also the name is not showed properly.
In example it is:
{unknown key: BlackSunCannon}
under unit (green text)

**Comment by speed2CZ** [comment]
my guess is has something to do this this commit https://github.com/FAForever/fa-coop/commit/5d0973508c5600d979e74f8eed66aa3683bf1f1b when localization folders got moved

**Comment by ChrisKitching** [comment]
It looks to be another one like https://github.com/FAForever/fa/commit/23f60077bfde0990bed95952972d04d16ec2ddcb

Oddly, FA's localisation file for everything *except* english has a copy of these keys.

I'll merge missing keys from stock, that ought to fix this.

**Comment by ChrisKitching** [comment]
Okay, amusingly, the base game's english localisation file doesn't contain a value for the key `BlackSunCannon`.

... Does this even work in unmodded FA?

**Comment by speed2CZ** [comment]
everything worked before update

**Comment by speed2CZ** [comment]
Fixed by above ^^
