### ISSUE TITLE
Aeon 1

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#45]
Managed to finish (yay)
Audio for senior commander dying was the junior commander dying.
Walls

Are some other errors in the logs so take a look anyway.

https://gist.github.com/MattDeering/d87e073d1ebd02b202ce
https://gist.github.com/MattDeering/a1ca84b299c993313eac

eggroll:
https://gist.github.com/theeggroll/167f8cfd5f2b488ad8e6
https://gist.github.com/theeggroll/86d6c0cdd16c26180328

**Comment by ChrisKitching** [comment]
Missing localisation keys added with https://github.com/FAForever/fa/commit/23f60077bfde0990bed95952972d04d16ec2ddcb

**Comment by speed2CZ** [comment]
Expect the last warning when clicking on close button after finishing it should all all fixed. That one is common for all missions. So closing.
