### ISSUE TITLE
Cybran 6 as played by another group

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#47]
I told some guys about how to test co op missions, here is their report
Dudred's Logs:
https://gist.github.com/anonymous/808ef4db12bf30c8941c
https://gist.github.com/anonymous/7e0d62c04f699a4e920d

GuatelupeLopez's Logs:
https://gist.github.com/anonymous/fffc391c5def58ff0b4c
https://gist.github.com/anonymous/f1fd5e9cb3d652bc12b9

Vanilla Cybran Campaign Mission 6: "Freedom"
No bugs were apparent until the "Capture Black Sun" final objective was given, and the map expanded.
At this point, the UEF nuked the Aeon base 3 times, but the "Strategic Launch Detected" sound played 5 or 6 times. We destroyed all of the nuke launchers rather quickly, so I am not sure if destroying them stopped the sound from playing, or if they had finished playing the sound on their own. When we killed the UEF commander, the game immediately desync'd, but we didn't notice any differences between our two screens. We destroyed the T3 artillery in the UEF base, but continued to take occasional hits from T3 artillery, which we could not find anywhere. Finally, after capturing black sun; I clicked the "Fire Black Sun: End the Infinite War" button, and instantly failed the mission. Not entirely sure if that really is a bug.

**Comment by barrystaes** [comment]
After destroying the last green unit (naval factory) the cutscene started and lots of T3 spiders walked in .. our 2P COOP game desynced near instantly.

**Comment by speed2CZ** [comment]
Please open a new issue and include game.log and the replay
