### ISSUE TITLE
AI Eco

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#48]
Since @ChrisKitching deleted code that was giving AI infinite resources, we need to find another solution, right now AI in every mission is is epic eco crash

Washy made for me this code http://pastebin.com/VDH6iXwR that allows to set energy and mass mults for every army in each mission, so this can be adjusted very well with few play tests.

Problem is that this affects only buildings that already exists, any other building that AI builds/rebuilds is not affected anymore.

**Comment by MattDeering** [comment]
I've noticed this as well. Those mass fab changes really kill the power.

**Comment by ChrisKitching** [comment]
> Those mass fab changes really kill the power.

So give the AI more power generators in their starting base?

**Comment by speed2CZ** [comment]
More power will help is vanilla missions, but not in FA missions, since those missions were designed with infinite eco. They need some cheating code to multiply eco or complete deresign. And we dont want to change those missions too much since people want to play missions they are familiar with.

**Comment by ChrisKitching** [comment]
I think that's a bit of an exaggeration. Literally the only part that's "designed with infinite eco" is the economy side of things. The solution boils down to tweaking the AI's base. Giving them a few more mass fabs/power generators so it's balanced, maybe spawning them a few extra mass points near their base. It's certainly not the unassailable problem you make it out to be, and once done it should yield a more consistent experience.

**Comment by speed2CZ** [comment]
Should be fixed for most of the mission by
https://github.com/FAForever/fa-coop/commit/e0fe4ea709b8a8319d75de6acc6704a01bc5c50d
and
https://github.com/FAForever/fa/commit/256b6bf0576030c7883ac1684c571d8491195b84
