### ISSUE TITLE
Aeon 3

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#50]
![image](https://cloud.githubusercontent.com/assets/8985887/9157787/e93f7b06-3f4d-11e5-9aac-af269b34f807.png)

This is Arnold right now.

Got through the defence objective and destroyed all 3 bases but Arnold didn't teleport when we nearly killed him and became invincible.

lost my forever.log but here is game
https://gist.github.com/MattDeering/d599206b1362208380a4

**Comment by ChrisKitching** [comment]
Sounds very much like this problem:
https://github.com/FAForever/fa/pull/844

I'll poke sheeo to publish a new build tonight so your tests don't get ruined by things that're already fixed any more.

**Comment by speed2CZ** [comment]
this should be fixed already together will all mission where units were teleporting away, ACUs civ trucks, whatever

**Comment by MattDeering** [comment]
The update didn't get pushed till 46. Haven't tested since then.

**Comment by speed2CZ** [comment]
Ive just tested and managed to win, he teleported as he should, closing for now
