### ISSUE TITLE
FA 2

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#56]
continuous desync from beat 1. Also eggroll walked forward and died for me, popped up with mission over etc. For him he was still alive and couldn't actually die

My logs:
https://gist.github.com/MattDeering/1ef8b5edd31591f98b78
https://gist.github.com/MattDeering/1316d3fe457f8c4127f1

eggrolls:
https://gist.github.com/theeggroll/e41471e96ab40f61e1ad
https://gist.github.com/theeggroll/e0c2b824f8715ba92acb

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/faf-coop-maps/commit/02c07cea67e1bcab3857ef56b1d255b3c4262aa2
