### ISSUE TITLE
Cybran 4v2

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#59]
So things up until the first expansion worked, then the aeon attack on the node happens literally 10 seconds after the operation area expands and you physically cannot get there in time to defeat the aeon assault. (We had transports at the ready with units and a full air force and a full navy and nothing got there in time)
https://gist.github.com/theeggroll/b81b3a932d15971efaf5
https://gist.github.com/theeggroll/c6b73f54f3c9c965fb48
Deerings logs
https://gist.github.com/MattDeering/97f7c8ee635d5d9e8148
https://gist.github.com/MattDeering/68aad9a4b95d2814c918

**Comment by Katharsas** [comment]
Can confirm. It is possible, if you build like 150 t2 gunships before expanding, but if you get catched by surprise ist not possible.
