### ISSUE TITLE
UEF 1

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#60]
Few errors in our log + we never got Thompson as an ally. The UEF base didnt show up at all.
https://gist.github.com/theeggroll/0625bde0a55dac5911ef
https://gist.github.com/theeggroll/fb9ddf77b3124da09ccd
Deering log
https://gist.github.com/MattDeering/21661dfd2507874bed3e
https://gist.github.com/MattDeering/c90c6076f326d82fe8fe

**Comment by speed2CZ** [comment]
Problem is in this function
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E01/SCCA_Coop_E01_script.lua#L887
When the function gets called it doesn't set alliances. Strange thing is that if I call that function during one of the first objectives it works.

**Comment by speed2CZ** [comment]
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_E01/SCCA_Coop_E01_script.lua#L842
after this dialogue is played table with human players gets empty

That makes no sense to me

**Comment by Crotalus** [comment]
Yeah something fishy is going on, seems like the map is "reloaded" somehow, like it jumps into another lua state from that Dialogue code. Too tired to try to debug it now though.

Try find out the codepath ScenarioFramework.Dialogue takes right before StartMission7

**Comment by Crotalus** [comment]
Ok, seems like the AttackManager imports the map file again when using build conditions defined in the save file.

So short story is do not initialize variables in the scenario script file, only if they are constants. Move all instances of `ScenarioInfo.HumanPlayers = {}` from scenario files into the BeginSession() @ simInit.lua.

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/fa-coop/commit/dd43045c09727d379468dd6f18dd8117e94e98fe
and
https://github.com/FAForever/faf-coop-maps/commit/aca88d721617415f7c3fa516aa4d32d3f4d94541
