### ISSUE TITLE
UEF 4

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#63]
Worked fine until quantam Gate bugged out and Dr Sweeny's truck did not successfully teleport.
fa units are available and im not sure if you're supposed to start with access to all t2 units, ill leave a comment in this shortly as to whether or not that is consistent with original sup com. Otherwise objectives and everything else seemed to be working quite nicely.
My logs:
https://gist.github.com/theeggroll/601d404b706e30ad351a
https://gist.github.com/theeggroll/6797fdd737db19df22e5
Deerings logs:
https://gist.github.com/MattDeering/812ca14867a8d86740d3
https://gist.github.com/MattDeering/908194b4eee919c3af9e

**Comment by speed2CZ** [comment]
teleporting out UEF and Cybran units is broken right now https://github.com/FAForever/fa/issues/865
if you run into this in other missions no need to report that again

**Comment by theeggroll** [comment]
Unit resitrictions need to be fixed tho

**Comment by speed2CZ** [comment]
Fixed, units teleport out now
