### ISSUE TITLE
FA 4 

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#64]
Holy shit this mission is so broken.
Upon Launching you just get a giant map with 0 fog of war and not a single unit on the whole map.
https://gist.github.com/theeggroll/0982015f6a8377e2f535
https://gist.github.com/theeggroll/3e3a145b41a1ddbcacd3

**Comment by speed2CZ** [comment]
already fixed https://github.com/FAForever/faf-coop-maps/commit/6b7a5e9a251a9474ad6783306f888467d1ae315f
