### ISSUE TITLE
FA 2

### ISSUE THREAD

**Issue by theeggroll** [FAForever/faf-coop-maps#77]
Random desync + difficulty is SUPER low now (first objective didnt even have t2 units in it .-.)
https://gist.github.com/theeggroll/cf1f3f010540b407279b
https://gist.github.com/theeggroll/fcf2ca19434dbd8bca27

**Comment by Sheeo** [comment]
Why was this close?

**Comment by theeggroll** [comment]
I didn't refaf after the update so it was an old version of the map.
