### ISSUE TITLE
Blanace/QoL issue with destroyed MEX's on prebuilts

### ISSUE THREAD

**Issue by HerptyDerpoty** [FAForever/faf-coop-maps#87]
On the maps where you spawn in an area with destroyed t3 mex as your only mass expansions means you haev access to upwards of 20k mass from the get go and can forgo building MEX for a long time.
Maybe have the first 3-4 closest MEX spots be empty adn have the rest be as original FA.

**Comment by speed2CZ** [comment]
Ive never seen this as an issue, it grand kick start to the mission. I guess rather than removing it they could be replaced by T2 mexes so isnt such a huge mass boost

**Comment by speed2CZ** [comment]
Replaced wrecked T3 mexes/factories by T2 and T1 for:
FA M2 https://github.com/FAForever/faf-coop-maps/commit/3a621ef5044b56049f9495062e38c461894a8503
FA M3 https://github.com/FAForever/faf-coop-maps/commit/e75a6ae75a622c8b84b5dd3875540acb00e2b460
FA M4 https://github.com/FAForever/faf-coop-maps/commit/04370365ba31ccab65abcb732e1a2f5437a8debd
