### ISSUE TITLE
FA 1 - UEF

### ISSUE THREAD

**Issue by Cmdrd** [FAForever/faf-coop-maps#88]
Playing the FA campaign Black Day as UEF doesn't expand after completing mission 3, killing the Aeon(order) ACU. 

During mission 3, once the initial dialogue the assignment of moving the trucks mission is played, no other dialogue events work. I have inserted log flags at numerous points right before these clips are supposed to play and these flags hit the logs, so the game is progressing through the code properly at these points, but something with regards to the ScenarioFramework.Dialogue doesn't appear to be working properly. I tested every piece of dialogue used in that script where only a voice over was played by copying them all to after repairing the shield and they play correctly. I'm thinking this is the reason why mission 4 doesn't start because that is dependent on the Dialogue function.

**Comment by speed2CZ** [comment]
Should be fixed by this https://github.com/FAForever/faf-coop-maps/commit/9deecfd11c636b1e3ce4dd02edb3cb73aba361ad
